-- EXECUTE WITH SYSDBA
ALTER SESSION SET "_ORACLE_SCRIPT"=TRUE;

CREATE USER BLOG IDENTIFIED BY BLOG;
GRANT CREATE SESSION TO BLOG;
GRANT CONNECT TO BLOG;

GRANT CREATE SESSION, CREATE TABLE, CREATE VIEW, CREATE SEQUENCE, CREATE PROCEDURE, CREATE TRIGGER TO BLOG;

ALTER USER BLOG QUOTA UNLIMITED ON USERS;
ALTER USER BLOG QUOTA 100M ON USERS;

CREATE TABLESPACE BLOG_TS
    DATAFILE 'BLOG_TS01.dbf'
    SIZE 500M
    AUTOEXTEND ON
    NEXT 50M
    MAXSIZE 10G
    EXTENT MANAGEMENT LOCAL
    SEGMENT SPACE MANAGEMENT AUTO;

ALTER USER BLOG DEFAULT TABLESPACE BLOG_TS;
ALTER USER BLOG QUOTA UNLIMITED ON BLOG_TS;

