CREATE SEQUENCE BLOG_AUTHOR_SEQ
START WITH
1
INCREMENT BY 1 MINVALUE 1 MAXVALUE 9999
NOCACHE
NOCYCLE;

CREATE SEQUENCE BLOG_COURSE_SEQ
START WITH
1
INCREMENT BY 1 MINVALUE 1 MAXVALUE 9999
NOCACHE
NOCYCLE;

CREATE SEQUENCE BLOG_SUBSCRIPTION_SEQ
START WITH
1
INCREMENT BY 1 MINVALUE 1 MAXVALUE 9999
NOCACHE
NOCYCLE;

CREATE SEQUENCE BLOG_NOTES_SEQ
START WITH
1
INCREMENT BY 1 MINVALUE 1 MAXVALUE 9999
NOCACHE
NOCYCLE;

CREATE SEQUENCE BLOG_DOCS_SEQ
START WITH
1
INCREMENT BY 1 MINVALUE 1 MAXVALUE 9999
NOCACHE
NOCYCLE;
