services:
  jboss:
    image: quay.io/wildfly/wildfly:28.0.0.Final-jdk17
    container_name: jboss_container_prod
    environment:
      WILDFLY_USERNAME: user
      WILDFLY_PASSWORD: user1234
    ports:
      - "8080:8080"
      - "9990:9990"
    # volumes:
    #  - ./compose/jboss/standalone-full.xml:/bitnami/wildfly/configuration/standalone.xml:ro
