//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2024.09.15 at 06:09:50 PM PET 
//

@jakarta.xml.bind.annotation.XmlSchema(namespace = "http://tempuri.org/", elementFormDefault = jakarta.xml.bind.annotation.XmlNsForm.QUALIFIED)
package edu.systemia.auditing_entities.infrastructure.wsdl;
