//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2024.09.29 at 01:12:02 PM PET 
//


package edu.systemia.auditing_entities.infrastructure.wsdl;

import jakarta.xml.bind.annotation.*;


/**
 * <p>Java class for anonymous complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="SubtractResult" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
	"subtractResult"
})
@XmlRootElement(name = "SubtractResponse")
public class SubtractResponse {

	@XmlElement(name = "SubtractResult")
	protected int subtractResult;

	/**
	 * Gets the value of the subtractResult property.
	 */
	public int getSubtractResult() {
		return subtractResult;
	}

	/**
	 * Sets the value of the subtractResult property.
	 */
	public void setSubtractResult(int value) {
		this.subtractResult = value;
	}

}
