#logging:
#  level:
#    org:
#      hibernate: INFO

server:
  servlet:
    context-path: /api/blogs

spring:
  application:
    name: auditing-entities

  datasource:
    primary:
      url: jdbc:oracle:thin:@localhost:1521:xe
      username: BLOG
      password: BLOG
      driver-class-name: oracle.jdbc.OracleDriver
    secondary:
      url: jdbc:mariadb://localhost:3306/audit_db
      username: blog
      password: blog
      driver-class-name: org.mariadb.jdbc.Driver
  
  jpa:
    #    hibernate:
    #      ddl-auto: update
    show-sql: true
    database: oracle
    properties:
      hibernate:
        #        generate_statistics: true
        format_sql: true
    open-in-view: false
        