#logging:
#  level:
#    org:
#      hibernate: INFO

server:
  servlet:
    context-path: /api/blogs

spring:
  application:
    name: auditing-entities

  datasource:
    jndi-name: java:/blog_DS
    oracle:
      jdbcUrl: jdbc:oracle:thin:@localhost:51521:xe
      username: BLOG
      password: BLOG
      driver-class-name: oracle.jdbc.OracleDriver
    mariadb:
      jdbcUrl: jdbc:mariadb://localhost:3306/audit_db
      username: blog
      password: blog
      driver-class-name: org.mariadb.jdbc.Driver

  
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    database: oracle # oracle or mysql
    database-platform: org.hibernate.dialect.OracleDialect
    properties:
      hibernate:
        # generate_statistics: true
        format_sql: true
        session_factory:
          interceptor: edu.systemia.auditing_entities.infrastructure.persistence.interceptors.AppInterceptor
    open-in-view: true

#logging:
#  level:
#    org:
#      hibernate: DEBUG
#      springframework.orm.jpa: DEBUG

# ORACLE or MARIADB
use-database:
  datasource: ORACLE
