image: maven:3.9.5-amazoncorretto-17-debian

workflow:
  rules:
    - if: $CI_COMMIT_BRANCH == 'main'

stages:
  - verify
  - compile
  - test
  - build

job-verify:
  stage: compile
  script:
    - ./mvnw clean compile

job-compile:
  stage: compile
  script:
    - ./mvnw clean compile

job-test:
  stage: test
  script:
    - ./mvnw clean test jacoco:report
  artifacts:
    when: always
    reports:
      junit: target/surefire-reports/TEST-*.xml
      coverage_report:
        coverage_format: jacoco
        path: target/site/jacoco/jacoco.xml
    paths:
      - target/surefire-reports/

job-build:
  stage: build
  script:
    - ./mvnw clean install

  artifacts:
    paths:
      - deploy/