CREATE TABLE BLOG_AUTHORS(
	AT_ID NUMBER(19,0) NOT NULL ENABLE,
	AT_ACTIVE VARCHAR2(1 CHAR) NOT NULL ENABLE,
	CREATED_AT TIMESTAMP (6) NOT NULL ENABLE,
	AT_FIRSTNAME VARCHAR2(100 CHAR),
	AT_LASTNAME VARCHAR2(100 CHAR),
	UPDATED_AT TIMESTAMP (6),
	PRIMARY KEY (AT_ID)
);

CREATE TABLE BLOG_COURSES(
	CO_ID NUMBER(19,0) NOT NULL ENABLE,
	CO_NAME VARCHAR2(100 CHAR) NOT NULL ENABLE,
	CO_PUBLISHIED NUMBER(1),
	PRIMARY KEY (CO_ID)
);

CREATE TABLE BLOG_SUBSCRIPTION(
	SUB_ID NUMBER(19) NOT NULL ENABLE,
	AT_ID NUMBER(19),
	CO_ID NUMBER(19),
	CREATE_AT DATE,
	PRIMARY KEY (SUB_ID),
	CONSTRAINT FK_AT_ID FOREIGN KEY (AT_ID) REFERENCES BLOG_AUTHORS(AT_ID),
	CONSTRAINT FK_CO_ID FOREIGN KEY (CO_ID) REFERENCES BLOG_COURSES(CO_ID)
);

--- CREATE TABLE NOTES
CREATE TABLE BLOG_NOTES(
	NO_ID NUMBER(19) NOT NULL ENABLE,
	NOTE_PARTIAL NUMBER(19),
	CREATE_AT DATE,
	AT_ID NUMBER(19),
	PRIMARY KEY (NO_ID),
	CONSTRAINT NOTES_FK_AT_ID FOREIGN KEY (AT_ID) REFERENCES BLOG_AUTHORS(AT_ID)
);

-- ADD COLUMN AUTHOR
COMMENT ON COLUMN BLOG_AUTHORS.AT_ACTIVE IS 'Value between Y or N';

ALTER TABLE BLOG_AUTHORS ADD CONSTRAINT AT_CK_ACTIVE CHECK(AT_ACTIVE IN ('Y', 'N'));
ALTER TABLE BLOG_AUTHORS ADD CONSTRAINT AT_CK_ACTIVE_NOT_NULL CHECK(AT_ACTIVE IS NOT NULL);
ALTER TABLE BLOG_COURSES ADD CONSTRAINT CK_CO_PUBLISHIED CHECK (CO_PUBLISHIED IN (0, 1));