#logging:
#  level:
#    org:
#      hibernate: INFO

environment: development
application:
  version: 01.00.00-SNAPSHOT

server:
  servlet:
    context-path: /auditing-tables/api/blogs
    multipart:
      max-file: 10MB
      max-request-size: 10MB

spring:
  application:
    name: auditing-entities
  jackson:
    time-zone: Europe/Paris
    property-naming-strategy: LOWER_CAMEL_CASE

  messages:
    basename: messages
    encoding: ISO-8859-15 # UTF-8
    fallback-to-system-locale: false

  datasource:
    # jndi-name: java:jboss/OracleDS
    oracle:
      jdbcUrl: jdbc:oracle:thin:@localhost:49165:xe
      username: BLOG
      password: BLOG
      driver-class-name: oracle.jdbc.OracleDriver
    mariadb:
      jdbcUrl: jdbc:mariadb://localhost:3306/audit_db
      username: blog
      password: blog
      driver-class-name: org.mariadb.jdbc.Driver

  
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    database: oracle # oracle or mysql
    database-platform: org.hibernate.dialect.OracleDialect
    properties:
      hibernate:
        # generate_statistics: true
        format_sql: true
        session_factory:
          interceptor: edu.systemia.auditing_entities.infrastructure.persistence.interceptors.AppInterceptor
#    open-in-view: true

#logging:
#  level:
#    org:
#      hibernate: DEBUG
#      springframework.orm.jpa: DEBUG

# ORACLE or MARIADB
use-database:
  datasource: ORACLE
